export const SEVIYE = { 1: "Seviye 1 · Yan yana", 2: "Seviye 2 · İşbirliği", 3: "Seviye 3 · Sohbet", 4: "Seviye 4 · Ortak proje" };
// Her görevin "roller" listesi yapboz mantığıdır: görev, roller paylaşılmadan tamamlanamaz.
export const GOREVLER = [
  { id: "yapboz", baslik: "Ortak yapboz", seviye: 1, sure: 15, puan: 10, aciklama: "Kütüphanede ya da sınıfta bir yapbozun bir bölümünü birlikte tamamlayın. Konuşmanız şart değil, yan yana çalışmanız yeter.", kanit: "Yapbozun son halini çekin. Yüzler görünmesin.", roller: ["Kenar parçalarını bulan", "Renkleri ayıran", "Parçaları birleştiren"] },
  { id: "cizim", baslik: "Sıralı çizim", seviye: 1, sure: 10, puan: 10, aciklama: "Bir kâğıda sırayla ekleme yaparak ortak bir resim çizin. Her kişi iki dakika çizer, kâğıt bir sonrakine geçer.", kanit: "Tamamlanan çizimi çekin.", roller: ["İlk çizgiyi atan", "Rengi seçen", "Son dokunuşu yapan"] },
  { id: "masa", baslik: "Masa oyunu turu", seviye: 1, sure: 15, puan: 10, aciklama: "Kütüphanede ya da teneffüste 15 dakika bir masa oyunu oynayın (dama, satranç, kutu oyunu).", kanit: "Oyun tahtasını çekin. Yüzler görünmesin.", roller: ["Kuralları okuyan", "Oyunu kuran", "Skoru tutan"] },
  { id: "bayrak", baslik: "Takım bayrağı", seviye: 2, sure: 20, puan: 15, aciklama: "Takımınızın adını anlatan bir bayrak ya da logo tasarlayın. Renkleri ve sembolü birlikte seçin.", kanit: "Bayrağın fotoğrafını çekin.", roller: ["Çizen", "Renklendiren", "Yazıyı yazan"] },
  { id: "afis", baslik: "Okul etkinliği afişi", seviye: 2, sure: 25, puan: 20, aciklama: "Okulda yapılacak hayali bir etkinlik için afiş hazırlayın (kitap günü, bilim şenliği gibi).", kanit: "Afişi tam görünecek şekilde çekin.", roller: ["Başlığı yazan", "Görseli çizen", "Düzeni yapan"] },
  { id: "foto-av", baslik: "Okulda nesne avı", seviye: 2, sure: 20, puan: 15, aciklama: "Okulda 5 nesne bulun: yuvarlak bir şey, yeşil bir şey, eski bir şey, size güzel gelen bir şey, bir yazı. Her birini kâğıda not edin ve fotoğraflayın.", kanit: "Nesnelerin fotoğraflarını tek karede ya da yan yana çekin. İnsan yüzü olmasın.", roller: ["Listeyi tutan", "Nesneyi bulan", "Fotoğrafı çeken"] },
  { id: "ortak3", baslik: "Ortak üç şey", seviye: 3, sure: 10, puan: 15, aciklama: "Takım olarak hepinizde ortak olan üç şey bulun (sevdiğiniz bir yemek, bir hayvan, bir hayal gibi). Hepsini kâğıda yazın.", kanit: "Yazdığınız kâğıdı çekin.", roller: ["Soruları soran", "Cevapları yazan", "Ortakları ayıklayan"] },
  { id: "roportaj", baslik: "Mini röportaj", seviye: 3, sure: 15, puan: 20, aciklama: "Bir okul çalışanına (öğretmen, kütüphaneci, müdür yardımcısı) izin alarak 3 soru sorun ve cevapları yazın.", kanit: "Cevapların yazılı olduğu kâğıdı çekin.", roller: ["Soru soran", "Not alan", "Teşekkür edip özetleyen"] },
  { id: "slogan", baslik: "Slogan ve tanıtım kartı", seviye: 3, sure: 20, puan: 20, aciklama: "Takımınız için bir slogan yazın ve küçük bir tanıtım kartı hazırlayın: takım adı, slogan, herkesin sevdiği bir şey.", kanit: "Kartı çekin.", roller: ["Sloganı öneren", "Kartı süsleyen", "Yazıyı yazan"] },
  { id: "bahce", baslik: "Küçük bahçe düzenlemesi", seviye: 4, sure: 30, puan: 25, aciklama: "Okul bahçesinde izin aldığınız küçük bir köşeyi düzenleyin: çöp toplayın, çiçek sulayın ya da bir saksı yerleştirin.", kanit: "Önce ve sonra fotoğrafı çekin. Yüzler görünmesin.", roller: ["İzin alıp planlayan", "Temizliği yapan", "Önce/sonra fotoğrafını çeken"] },
  { id: "storyboard", baslik: "Tanıtım videosu planı", seviye: 4, sure: 30, puan: 25, aciklama: "Okulunuzu tanıtan 1 dakikalık bir video için sahne sahne çizimli bir plan (storyboard) hazırlayın.", kanit: "Planın fotoğrafını çekin.", roller: ["Hikâyeyi kuran", "Sahneleri çizen", "Metni yazan"] },
  { id: "pano", baslik: "Kitap önerisi panosu", seviye: 4, sure: 25, puan: 20, aciklama: "Her biriniz sevdiğiniz bir kitabı ya da filmi önerin ve hepsini tek bir panoda toplayın.", kanit: "Panoyu çekin.", roller: ["Panoyu düzenleyen", "Önerileri yazan", "Süsleyen"] }
];