// Bilgi kartları: ön yüz soru ya da ipucu, arka yüz tek cümlelik cevap
export const RENK = { "Tarih": "#8a5a2b", "Coğrafya": "#3f6a86", "Bilim": "#2c5545", "Edebiyat ve sanat": "#7a4a6a", "Eğlenceli": "#a0522d" };
export const KARTLAR = [
  { k: "Tarih", o: "Türkiye Cumhuriyeti hangi tarihte ilan edildi?", a: "29 Ekim 1923." },
  { k: "Tarih", o: "İstanbul'u fetheden padişah kimdir?", a: "II. Mehmed (Fatih Sultan Mehmed), 1453'te." },
  { k: "Tarih", o: "Malazgirt Savaşı hangi yıl yapıldı?", a: "1071. Bu zaferle Anadolu'nun kapıları Türklere açıldı." },
  { k: "Tarih", o: "Çanakkale Deniz Zaferi hangi tarihte kazanıldı?", a: "18 Mart 1915." },
  { k: "Tarih", o: "Latin harflerine hangi yıl geçildi?", a: "1928, Harf Devrimi ile." },
  { k: "Tarih", o: "Bilinen en eski Türkçe yazılı metinler hangileri?", a: "Orhun Yazıtları (8. yüzyıl)." },
  { k: "Tarih", o: "Türk kadınına milletvekili seçme ve seçilme hakkı ne zaman verildi?", a: "1934'te." },
  { k: "Tarih", o: "TBMM hangi tarihte açıldı?", a: "23 Nisan 1920." },
  { k: "Tarih", o: "Ankara ne zaman başkent oldu?", a: "13 Ekim 1923." },
  { k: "Tarih", o: "Atatürk hangi şehirde doğdu?", a: "Selanik'te." },
  { k: "Tarih", o: "Fransız Devrimi hangi yılda başladı?", a: "1789." },
  { k: "Tarih", o: "Piri Reis dünya haritasını hangi yıl çizdi?", a: "1513." },
  { k: "Coğrafya", o: "Türkiye'nin en yüksek dağı hangisi?", a: "Ağrı Dağı, yaklaşık 5137 metre." },
  { k: "Coğrafya", o: "Türkiye'nin en uzun nehri hangisi?", a: "Kızılırmak, yaklaşık 1355 km. Tamamı Türkiye sınırları içinde akar." },
  { k: "Coğrafya", o: "Türkiye'nin en büyük gölü hangisi?", a: "Van Gölü." },
  { k: "Coğrafya", o: "Dünyanın en büyük okyanusu hangisi?", a: "Büyük Okyanus (Pasifik)." },
  { k: "Coğrafya", o: "Dünyanın en uzun nehri genellikle hangisi sayılır?", a: "Nil, yaklaşık 6650 km." },
  { k: "Coğrafya", o: "Ekvator Dünya'yı hangi iki yarım küreye ayırır?", a: "Kuzey ve Güney yarım küre." },
  { k: "Coğrafya", o: "Dünyada kaç kıta var?", a: "7 kıta (yedi kıta modeline göre)." },
  { k: "Coğrafya", o: "Dünyanın en küçük kıtası hangisi?", a: "Avustralya (Okyanusya)." },
  { k: "Coğrafya", o: "Dünyanın bilinen en derin noktası neresi?", a: "Mariana Çukuru, yaklaşık 11 km derinlikte." },
  { k: "Coğrafya", o: "Türkiye'nin para birimi nedir?", a: "Türk Lirası." },
  { k: "Bilim", o: "Suyun kimyasal formülü nedir?", a: "H₂O: iki hidrojen, bir oksijen." },
  { k: "Bilim", o: "Işık bir saniyede yaklaşık ne kadar yol alır?", a: "Yaklaşık 300.000 km." },
  { k: "Bilim", o: "İnsan vücudunun en büyük organı hangisi?", a: "Deri." },
  { k: "Bilim", o: "Güneş Sistemi'nin en büyük gezegeni hangisi?", a: "Jüpiter." },
  { k: "Bilim", o: "Güneş Sistemi'nde kaç gezegen var?", a: "8. Plüton 2006'da cüce gezegen sayıldı." },
  { k: "Bilim", o: "DNA'nın açılımı nedir?", a: "Deoksiribonükleik asit." },
  { k: "Bilim", o: "Dünya Güneş'in etrafındaki turunu ne kadar sürede tamamlar?", a: "Yaklaşık 365 gün 6 saat. Artık yıl bu yüzden var." },
  { k: "Bilim", o: "Bitkiler fotosentezde hangi gazı alıp hangisini verir?", a: "Karbondioksit alır, oksijen verir." },
  { k: "Bilim", o: "Altının element sembolü nedir?", a: "Au." },
  { k: "Bilim", o: "İnsan kalbi kaç odacıktan oluşur?", a: "4: iki kulakçık, iki karıncık." },
  { k: "Bilim", o: "Oda sıcaklığında sıvı olan metal hangisi?", a: "Cıva." },
  { k: "Bilim", o: "Ses hangi ortamda yayılamaz?", a: "Boşlukta." },
  { k: "Bilim", o: "Yetişkin insan beyninde yaklaşık kaç nöron vardır?", a: "Yaklaşık 86 milyar olduğu tahmin ediliyor." },
  { k: "Edebiyat ve sanat", o: "“Çalıkuşu” romanının yazarı kim?", a: "Reşat Nuri Güntekin." },
  { k: "Edebiyat ve sanat", o: "İstiklal Marşı'nın şairi kim?", a: "Mehmet Akif Ersoy." },
  { k: "Edebiyat ve sanat", o: "“Sefiller” romanını kim yazdı?", a: "Victor Hugo." },
  { k: "Edebiyat ve sanat", o: "Mona Lisa'yı kim yaptı?", a: "Leonardo da Vinci." },
  { k: "Edebiyat ve sanat", o: "“Romeo ve Juliet” kimin eseri?", a: "William Shakespeare." },
  { k: "Edebiyat ve sanat", o: "Mimar Sinan'ın “ustalık eserim” dediği yapı hangisi?", a: "Edirne'deki Selimiye Camii." },
  { k: "Edebiyat ve sanat", o: "“Kürk Mantolu Madonna” kimin romanı?", a: "Sabahattin Ali." },
  { k: "Edebiyat ve sanat", o: "Mevlânâ'nın ünlü eseri hangisi?", a: "Mesnevi." },
  { k: "Edebiyat ve sanat", o: "Beethoven'ın 9. Senfonisi'nin ünlü bölümü hangi adla bilinir?", a: "“Neşeye Övgü”. Müziği Avrupa Marşı olarak da kullanılır." },
  { k: "Eğlenceli", o: "Satrançta bir oyuncunun kaç taşı vardır?", a: "16." },
  { k: "Eğlenceli", o: "Ahtapotun kaç kalbi vardır?", a: "3." },
  { k: "Eğlenceli", o: "Uçabilen tek memeli hayvan hangisi?", a: "Yarasa." },
  { k: "Eğlenceli", o: "Modern Olimpiyat Oyunları ilk hangi şehirde yapıldı?", a: "Atina, 1896." },
  { k: "Eğlenceli", o: "Bir yılda kaç ay 31 gün çeker?", a: "7 ay." },
  { k: "Eğlenceli", o: "Göbeklitepe hakkında ne biliyorsun?", a: "Yaklaşık 11.000 yıllık, bilinen en eski anıtsal tapınak alanlarından biri. UNESCO Dünya Mirası." },
  { k: "Eğlenceli", o: "Bir futbol takımı sahada kaç kişiyle oynar?", a: "11 kişiyle." }
];
